In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.neighbors import NearestNeighbors

# Data

In [40]:
df = pd.read_csv('../data/cleaned-table/basic_info.csv')
df

hotel_id   latitude   longitude    price_mean  score_mean  star_number  \
0        39339  15.905757  108.312703  9.197257e+05       83.00            4   
1        42896  10.331910  106.031753  3.388635e+05       83.25            0   
2        30354  10.774900  106.682381  4.545450e+05       87.50            2   
3         3460  17.476322  106.623169  9.337925e+04       86.00            1   
4        41862  20.218610  105.921169  2.430907e+05       93.50            3   
...        ...        ...         ...           ...         ...          ...   
3995     44066  12.244705  109.194610  2.363636e+06       80.00            5   
3996     45962  12.217711  109.196038  8.887748e+05       96.00            2   
3997     42417  13.099170  109.310112  2.077920e+05       76.50            1   
3998     42919  20.830410  104.691933  1.718180e+05       82.50            0   
3999     38023  11.929950  108.428093  6.822721e+05       85.00            0   

      tours  luggage_storage  laundry_service  
0         1                1                1  
1         1                1                1  
2        -1                1                1  
3         1                1                1  
4         1                1                1  
...     ...              ...              ...  
3995     -1               -1                1  
3996      0                1                1  
3997     -1                1                1  
3998      1                1                1  
3999      0                1                1  

[4000 rows x 9 columns]

In [41]:
df.set_index('hotel_id')

latitude   longitude    price_mean  score_mean  star_number  tours  \
hotel_id                                                                        
39339     15.905757  108.312703  9.197257e+05       83.00            4      1   
42896     10.331910  106.031753  3.388635e+05       83.25            0      1   
30354     10.774900  106.682381  4.545450e+05       87.50            2     -1   
3460      17.476322  106.623169  9.337925e+04       86.00            1      1   
41862     20.218610  105.921169  2.430907e+05       93.50            3      1   
...             ...         ...           ...         ...          ...    ...   
44066     12.244705  109.194610  2.363636e+06       80.00            5     -1   
45962     12.217711  109.196038  8.887748e+05       96.00            2      0   
42417     13.099170  109.310112  2.077920e+05       76.50            1     -1   
42919     20.830410  104.691933  1.718180e+05       82.50            0      1   
38023     11.929950  108.428093  6.822721e+05       85.00            0      0   

          luggage_storage  laundry_service  
hotel_id                                    
39339                   1                1  
42896                   1                1  
30354                   1                1  
3460                    1                1  
41862                   1                1  
...                   ...              ...  
44066                  -1                1  
45962                   1                1  
42417                   1                1  
42919                   1                1  
38023                   1                1  

[4000 rows x 8 columns]

# Training

In [85]:
nbrs = NearestNeighbors(n_neighbors=5, algorithm='ball_tree').fit(df.set_index('hotel_id'))

> Testing

In [92]:
test = df.set_index('hotel_id').values[0].reshape(1,-1)
nbrs.kneighbors(test, return_distance=False)

array([[   0,  403, 1310,  570, 3937]])

# Saving Model

In [87]:
import pickle 

knn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree').fit(df.set_index('hotel_id'))

# Its important to use binary mode 
knnPickle = open('knnpickle_file', 'wb') 

# source, destination 
pickle.dump(knn, knnPickle)                      

# Loading Model

In [93]:
# load the model from disk
loaded_model = pickle.load(open('knnpickle_file', 'rb'))

In [94]:
df.set_index('hotel_id').values[0].reshape(1,-1)

array([[1.59057565e+01, 1.08312703e+02, 9.19725714e+05, 8.30000000e+01,
        4.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [114]:
# input
hotel_id = 39339
# load data-to-model
hotel_info = df[df['hotel_id'] == 39339].index[0]
# check
test = df.set_index('hotel_id').values[hotel_info].reshape(1,-1)
result = loaded_model.kneighbors(test, return_distance=False)
result

array([[   0,  403, 1310,  570, 3937]])